version: '3.8'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/test
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    ports:
      - "9090:9090"

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test
    ports:
      - "5432:5432"